backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"
locale: "ru"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: Студсовет
    name: site
    editor:
      preview: false
    files:
      - label: Мультиссылка
        name: multilink
        file: "src/_data/multilink.yaml"
        fields:
          - { label: Заголовок, name: heading, widget: string, hint: Отображается на вкладке и если нет логотипа }
          - { label: Логотип, name: logo, widget: image, allow_multiple: false, required: false }
          - { label: Цвет текста, name: color, widget: color, required: false, allowInput: true }
          - { label: Цвет фона, name: background, widget: color, required: false, allowInput: true }
          - { label: Фоновый паттерн, name: pattern, widget: image, allow_multiple: false, required: false }
          - label: Список
            name: list
            widget: list
            types:
              - label: Подзаголовок
                name: heading
                widget: object
                fields:
                  - { label: Заголовок, name: heading, widget: string }
              - label: Параграф текста
                name: paragraph
                widget: object
                fields:
                  - { label: Параграф, name: text, widget: text }
              - label: Кнопка
                name: link
                widget: object
                fields:
                  - { label: Подпись, name: text, widget: string }
                  - { label: Ссылка, name: href, widget: string }
                  - { label: Цвет текста, name: color, widget: color, required: false, allowInput: true }
                  - { label: Цвет фона, name: color, widget: background, required: false, allowInput: true }
          - { label: Цвет соцсетей, name: fill, widget: color, required: false, allowInput: true }
          - { label: Цвет фона соцсетей, name: socialBg, widget: color, required: false, allowInput: true }
          - { label: ВКонтакте, name: vk, widget: string, required: false }
          - { label: Тик-Ток, name: tiktok, widget: string, required: false }
          - { label: Инстаграм, name: ig, widget: string, required: false }